# Introduction to pytorch
- [Pytorch Turotrial](https://pytorch.org/tutorials/beginner/nlp/pytorch_tutorial.html#sphx-glr-beginner-nlp-pytorch-tutorial-py) 에서 제공하는 튜토리얼을 실습해봅니다.

In [1]:
import torch
import torch.nn as nn
import torch.autograd as autograd
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

tensor([1., 2., 3.])


In [3]:
# Creates a marix
M_data = [[1., 2., 3.], [4., 5., 6.]]
M = torch.tensor(M_data)
print(M)

tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [4]:
# Create a 3D tensor of size 2x2x2
T_data = [[[1., 2.], [3., 4.]],
         [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [5]:
# Indexing
print(V[0])

tensor(1.)


In [6]:
# Get python number from Tensor
print(V[0].item())

1.0


In [7]:
# Indexing from Matrix then get a vecor
print(M[0])

tensor([1., 2., 3.])


In [8]:
# Indexing from 3D tensor thten get a Matrix
print(T[0])

tensor([[1., 2.],
        [3., 4.]])


- Integer types Tensor
    - torch.LongTensor()

In [9]:
T = torch.LongTensor(T_data)
print(T)

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- Random number of Tensor

In [10]:
# 3 x 4 x 5 Random Number of Tensor
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


- Concatetnate

In [11]:
# 2 x 5 random tensor
x_1 = torch.randn(2, 5)

# 3 x 5 random tensor
y_1 = torch.randn(3, 5)

# concatenate
z_1 = torch.cat([x_1, y_1])
print(z_1)
print(z_1.shape)

tensor([[-0.8029,  0.2366,  0.2857,  0.6898, -0.6331],
        [ 0.8795, -0.6842,  0.4533,  0.2912, -0.8317],
        [-0.5525,  0.6355, -0.3968, -0.6571, -1.6428],
        [ 0.9803, -0.0421, -0.8206,  0.3133, -1.1352],
        [ 0.3773, -0.2824, -2.5667, -1.4303,  0.5009]])
torch.Size([5, 5])


In [12]:
# 2 x 3 random tensor
x_2 = torch.randn(2, 3)

# 2 x 5 random tensor
y_2 = torch.randn(2, 5)

# concatenate
z_2 = torch.cat([x_2, y_2], dim=1)
print(z_2)
print(z_2.shape)

tensor([[ 0.5438, -0.4057,  1.1341, -0.1473,  0.6272,  1.0935,  0.0939,  1.2381],
        [-1.1115,  0.3501, -0.7703, -1.3459,  0.5119, -0.6933, -0.1668, -0.9999]])
torch.Size([2, 8])


- Reshaping

In [13]:
# 2 x 3 x 4 크기의 Tensor
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12))
print(x.view(2, -1))
print(x)

tensor([[[ 0.4175, -0.2127, -0.8400, -0.4200],
         [-0.6240, -0.9773,  0.8748,  0.9873],
         [-0.0594, -2.4919,  0.2423,  0.2883]],

        [[-0.1095,  0.3126,  1.5038,  0.5038],
         [ 0.6223, -0.4481, -0.2856,  0.3880],
         [-1.1435, -0.6512, -0.1032,  0.6937]]])
tensor([[ 0.4175, -0.2127, -0.8400, -0.4200, -0.6240, -0.9773,  0.8748,  0.9873,
         -0.0594, -2.4919,  0.2423,  0.2883],
        [-0.1095,  0.3126,  1.5038,  0.5038,  0.6223, -0.4481, -0.2856,  0.3880,
         -1.1435, -0.6512, -0.1032,  0.6937]])
tensor([[ 0.4175, -0.2127, -0.8400, -0.4200, -0.6240, -0.9773,  0.8748,  0.9873,
         -0.0594, -2.4919,  0.2423,  0.2883],
        [-0.1095,  0.3126,  1.5038,  0.5038,  0.6223, -0.4481, -0.2856,  0.3880,
         -1.1435, -0.6512, -0.1032,  0.6937]])
tensor([[[ 0.4175, -0.2127, -0.8400, -0.4200],
         [-0.6240, -0.9773,  0.8748,  0.9873],
         [-0.0594, -2.4919,  0.2423,  0.2883]],

        [[-0.1095,  0.3126,  1.5038,  0.5038],
         [ 0.6

- `requires_grad=True`

In [14]:
x = torch.tensor([1., 2., 3.], requires_grad=True)
y = torch.tensor([4., 5., 6.], requires_grad=True)
z = x + y
print(z)

tensor([5., 7., 9.], grad_fn=<AddBackward0>)


In [15]:
print(z.grad_fn)

In [16]:
s = z.sum()
print(s)
print(s.grad_fn)

tensor(21., grad_fn=<SumBackward0>)


- s 의 x0 에 대한 gradient 는 손으로 계산해 봐도 1 과연?

In [17]:
s.backward()
print(x.grad)
print(x.grad[0].item())

tensor([1., 1., 1.])
1.0


- 아래 코드 이해하기

In [18]:
# 2 x 2 random tensor
x = torch.randn(2, 2)
y = torch.randn(2, 2)

# default require_grad 가 어떤가?
print("default: ", x.requires_grad, y.requires_grad)

z = x + y
print("z.grad_fn", z.grad_fn)

# False 였던 requires_grad 를 변경
x = x.requires_grad_()
y = y.requires_grad_()

z = x + y
print(z.grad_fn)
print(z.requires_grad)

# z의 copy 본은 어떻게 되는가?
new_z = z.detach()
print(new_z.grad_fn)


default:  False False
z.grad_fn None
True
None


In [19]:
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
True
False
